export const SET_MOTOCYCLES = 'SET_MOTOCYCLES'
export const FETCH_STATUS_ERROR = 'FETCH_ERROR'
export const FETCH_STATUS_PENDING = 'FETCH_STATUS_PENDING'
export const SET_MOTOCYCLE_SELECTED = 'SET_MOTOCYCLE_SELECTED'